<footer >
                <div class="container">
                <div class="row footlink">
                    <div class="col">
                        <h4>省市旅游网站</h4>
                        <p>
                            <a href="#">山东省旅游局</a>
                        </p>
                    </div>
                    <div  class="col">
                        <h4>旅游行业协会网站</h4>
                        <p><a href="#">中国旅游行业协会</a></p>
                        <p><a href="#">山东省旅游行业协会</a></p> 
                        <p><a href="#">青岛饭店协会</a></p>
                        <p><a href="#">中国旅游商品装备网</a></p>
                    </div>
                    <div  class="col">
                        <h4>海外旅游网站</h4>
                        <p><a href="#">英国观光局</a></p>
                        <p><a href="#">韩国旅游发展局</a></p> 
                        <p><a href="#">香港旅游发展局</a></p>
                        <p><a href="#">台湾观光资讯网</a></p>
                    </div>
                    <div  class="col">
                        <h4>旅游区点网站</h4>
                        <p><a href="#">崂山风景区</a></p>
                        <p><a href="#">青岛海底世界</a></p> 
                        <p><a href="#">青岛茶山风景区</a></p>
                    </div>
                    <div  class="col">
                        <h4>酒店网站</h4>
                        <p>
                            <a href="#">青岛复盛大酒店</a>
                        </p>
                    </div>
                    <div  class="col">
                        <h4>旅行社网站</h4>
                        <p> <a href="#">青岛中青旅国际旅行社</a> </p>
                        <p> <a href="#">华青国际旅行社</a> </p>
                        <p> <a href="#">港中旅国际（山东）旅行社</a> </p>
                    </div>
                    <div  class="col">
                        <h4>其他旅游网站</h4>
                        <p> <a href="#">八喜旅游网</a> </p>
                        <p> <a href="#">青岛航空</a> </p>
                        <p> <a href="#">环球导航网</a> </p>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col copyright1">青岛市旅游发展委员会  青岛旅游信息中心  版权所有  保留所有权利</div>
                </div>
                <div class="row justify-content-center">
                    <div class="col copyright1">Copyright 2013, All rights reserved by Qingdao Tourism Information Centre</div>
                </div>
                <div class="row justify-content-center">
                    <div class="col copyright1">联系邮箱：85912037@163.com</div>               
                </div>
                <div class="row justify-content-center">
                        <a  href="#"> <img src="..\images\red.png" alt=""></a> 
                        <a  href="#"> <img src="..\images\logo.gif" alt=""></a>
                        <a  href="#"> <img src="..\images\gangting.gif" alt=""></a>              
                    </div>
            </div>
            </footer>