 <header class=" fixed">
                <div class="container-fluid setheight" >
                    <div class="row  align-items-center setheight">
                        <!-- logo -->
                        <div class="logomid">
                                <a href="./index.html">
                                    <h1></h1>
                                </a>
                        </div>
                        <!-- 导航收缩 -->
                        <div class="pos-r-b bighide">
                                <nav class="navbar ">
                                  <button class="navbar-toggler navbar-light bg-light" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
                                    <span class="navbar-toggler-icon"></span>
                                  </button>
                                </nav>
                        </div>
                        <div class="menu_block container-fluid" >
                            <nav class="row">
                                <ul class="col-xl-5">                            
                                    <li class="col-xl-4 ">
                                        <a href="./index.html">首页</a>
                                    </li>
                                    <li class="col-xl-4">
                                        <a href="#" class="sf-with-ul">关于青岛
                                        </a>
                                    </li>
                                    <li class="col-xl-4">
                                        <a href="#">畅游青岛</a>
                                    </li>
                                </ul>
                                <div class="col-xl-2"></div>
                                <ul class="col-xl-5">
                                    <li class="col-xl-4">
                                        <a href="#">在线商城</a>
                                    </li>
                                    <li class="col-xl-4">
                                        <a href="#">体验分享</a>
                                    </li>
                                    <li class="col-xl-4">
                                        <a href="#">意见征集</a>
                                    </li>
                                </ul>
                            </nav>
                            <div class="clear"></div>
                        </div>
                    </div>
            
                </div>
            </header> 
            <!-- 下拉菜单 576-991px-->
            <div class="collapse sonmenu" id="navbarToggleExternalContent">
                    <div class="bg-light">
                        <h3 class="text-white">
                            <a href="#">首页</a>
                        </h3>
                        <h3 class="text-white">
                            <a href="#">关于青岛</a>
                        </h3>
                        <h3 class="text-white">
                            <a href="#">畅游青岛</a>
                        </h3>
                        <h3 class="text-white">
                            <a href="#">在线商城</a>
                        </h3>
                        <h3 class="text-white">
                            <a href="#">体验分享</a>
                        </h3>
                        <h3 class="text-white">
                            <a href="#">在线调查</a>
                        </h3>
                        <!-- <span class="text-muted">Toggleable via the navbar brand.</span> -->
                    </div>
             </div> 